<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><?php echo $this->layout()->application_name; ?></a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <?php $url = parse_url($this->serverUrl(), PHP_URL_PATH); ?>
        <li <?php if (false !== strpos($url, '/')) echo 'class="active"' ?>><a href="/">HOME</a></li>
        <li <?php if (false !== strpos($url, '/aim-world')) echo 'class="active"' ?>><a href="/aim-world">ABOUT AIM WORLD</a></li>
        <li <?php if (false !== strpos($url, '/our-team')) echo 'class="active"' ?>><a href="/our-team">JOIN OUR TEAM</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>