<div class="row">
    <div class="col-md-8">
        <h1 class="logo logo--light"><span class="l"><?php echo $this->layout()->organization; ?></h1>
        <p class="description">
            <?php echo $this->layout()->description; ?>
        </p>
        <ul class="social-links">
            <li class="social-link">
                <i class="fa fa-facebook-official"></i>
            </li>
            <li class="social-link">
                <i class="fa fa-twitter-square"></i>              
            </li>

            <li class="social-link">
                <i class="fa fa-linkedin-square"></i>
            </li>
        </ul>
    </div>
    <div class="col-md-4">
        <button>Join Our Team</button>
    </div>
</div>